# Generated by Django 2.1.5 on 2019-02-14 12:51

from django.db import migrations, models
import django.db.models.deletion
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategoryThreshold',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Level')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Threshold Value')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
                ('value_range', models.CharField(blank=True, max_length=63, null=True, verbose_name='Value Range')),
                ('visibility', models.CharField(blank=True, max_length=63, null=True, verbose_name='Visibility')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Message')),
                ('background_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Background Colour')),
                ('foreground_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Foreground Colour')),
                ('pollutant', models.CharField(default='sp_AQI', max_length=15, verbose_name='Pollutant')),
            ],
            options={
                'verbose_name': 'Health Category Threshold',
                'verbose_name_plural': 'Health Category Thresholds',
                'db_table': 'health_category_threshold',
            },
        ),
        migrations.CreateModel(
            name='AQICategoryThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=2, serialize=False, verbose_name='Abbrevation')),
                ('lower_threshold_value', models.FloatField(blank=True, null=True, verbose_name='Lower Threshold Value')),
                ('upper_threshold_value', models.FloatField(blank=True, null=True, verbose_name='Upper Threshold Value')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
                ('background_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Background Colour')),
                ('foreground_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Foreground Colour')),
                ('pollutant', models.CharField(default='aqi', max_length=15, verbose_name='Pollutant')),
                ('units', models.CharField(choices=[('-', 'no units'), ('ug/m3', 'micro-gram per cubic meter'), ('ppm', 'parts per million'), ('ppb', 'parts per billion')], default='-', max_length=12, verbose_name='Units')),
            ],
            options={
                'verbose_name': 'AQI Category Threshold',
                'verbose_name_plural': 'AQI Category Thresholds',
                'db_table': 'aqi_category_threshold',
            },
        ),
        migrations.AddField(
            model_name='aqicategorythreshold',
            name='aqi_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aqi_category_thresholds', to='common.AQIOrganization', verbose_name='AQI Organization'),
        ),
        migrations.AddField(
            model_name='healthcategorythreshold',
            name='aqi_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_category_thresholds', to='common.AQIOrganization', verbose_name='AQI Organization'),
        ),
    ]
