# Generated by Django 2.1.5 on 2019-02-19 05:51

from django.db import migrations

AQI_CATEGORY_THRESHOLDS = [
    # AQI
    {
        "abbreviation": "G",
        "lower_threshold_value": 0,
        "upper_threshold_value": 50.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 50.01,
        "upper_threshold_value": 100.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 100.01,
        "upper_threshold_value": 150.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 150.01,
        "upper_threshold_value": 200.00,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 200.01,
        "upper_threshold_value": 300.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 300.01,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "aqi"
    },
    # PM2.5
    {
        "abbreviation": "G",
        "lower_threshold_value": 0,
        "upper_threshold_value": 15.4,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 15.5,
        "upper_threshold_value": 40.4,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 40.5,
        "upper_threshold_value": 65.4,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 65.5,
        "upper_threshold_value": 150.4,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 150.5,
        "upper_threshold_value": 250.4,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 250.5,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5",
        "units": "ug/m3"
    },
    # PM10
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 54.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 55.0,
        "upper_threshold_value": 154.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 155.0,
        "upper_threshold_value": 254.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 255.0,
        "upper_threshold_value": 354.0,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 355.0,
        "upper_threshold_value": 424.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 425.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10",
        "units": "ug/m3"
    },
    # SO2
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 35.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 36.0,
        "upper_threshold_value": 75.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 176.0,
        "upper_threshold_value": 185.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 186.0,
        "upper_threshold_value": 304.0,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 305.0,
        "upper_threshold_value": 604.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 605.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2",
        "units": "ppb"
    },
    # NO2
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 53.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 54.0,
        "upper_threshold_value": 100.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 101.0,
        "upper_threshold_value": 360.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 361.0,
        "upper_threshold_value": 649.0,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 650.0,
        "upper_threshold_value": 1249.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 1250.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2",
        "units": "ppb"
    },
    # O3
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 0.09,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 0.1,
        "upper_threshold_value": 0.124,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 0.126,
        "upper_threshold_value": 0.164,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 0.165,
        "upper_threshold_value": 0.204,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 0.205,
        "upper_threshold_value": 0.404,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 0.405,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3",
        "units": "ppm"
    },
    # CO
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 4.4,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 4.5,
        "upper_threshold_value": 9.4,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 9.5,
        "upper_threshold_value": 12.4,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 12.5,
        "upper_threshold_value": 15.4,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 15.5,
        "upper_threshold_value": 30.4,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 30.5,
        "upper_threshold_value": 999999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co",
        "units": "ppm"
    },
]


def insert_aqi_categories(apps, schema_editor):
    AQICategoryThreshold = apps.get_model(
        'common', 'AQICategoryThreshold')
    for aqi in AQI_CATEGORY_THRESHOLDS:
        AQICategoryThreshold.objects.get_or_create(**aqi)


def revert_aqi_categories(apps, schema_editor):
    AQICategoryThreshold = apps.get_model(
        'common', 'AQICategoryThreshold')
    AQICategoryThreshold.objects.filter(aqi_organization_id="USEPA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_eu_aqi_index_tables_data'),
    ]

    operations = [
        migrations.RunPython(insert_aqi_categories, revert_aqi_categories),
    ]
