# Generated by Django 2.1.5 on 2019-02-19 05:51

from django.db import migrations

AQI_CATEGORY_THRESHOLDS = [
    # AQI
    {
        "abbreviation": "G",
        "lower_threshold_value": 0,
        "upper_threshold_value": 50.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 50.01,
        "upper_threshold_value": 100.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 100.01,
        "upper_threshold_value": 150.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 150.01,
        "upper_threshold_value": 200.00,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 200.01,
        "upper_threshold_value": 300.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 300.01,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "sp_AQI"
    },
    # PM2.5
    {
        "abbreviation": "G",
        "lower_threshold_value": 0,
        "upper_threshold_value": 15.4,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 15.5,
        "upper_threshold_value": 40.4,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 40.5,
        "upper_threshold_value": 65.4,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 65.5,
        "upper_threshold_value": 150.4,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 150.5,
        "upper_threshold_value": 250.4,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 250.5,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm2.5"
    },
    # PM10
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 54.0,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 55.0,
        "upper_threshold_value": 154.0,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 155.0,
        "upper_threshold_value": 254.0,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 255.0,
        "upper_threshold_value": 354.0,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 355.0,
        "upper_threshold_value": 424.0,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 425.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "pm10"
    },
    # SO2
    # calculated from ppm to ug/m3 with T=22C
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 89.9,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 90.0,
        "upper_threshold_value": 144.9,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 145.0,
        "upper_threshold_value": 541.99,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 542.0,
        "upper_threshold_value": 803.99,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 804.0,
        "upper_threshold_value": 1595.99,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 1596.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "so2"
    },
    # NO2
    # calculated from ppm to ug/m3 with T=22C
    {
        "abbreviation": "F",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 1234.99,
        "description": "Fair - Minor Risk",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 1235.0,
        "upper_threshold_value": 2373.99,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 2374.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "no2"
    },
    # O3
    # calculated from ppm to ug/m3 with T=22C
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 167.99,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 168.0,
        "upper_threshold_value": 247.99,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 248.0,
        "upper_threshold_value": 326.99,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 327.0,
        "upper_threshold_value": 405.99,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 406.0,
        "upper_threshold_value": 802.99,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 803.0,
        "upper_threshold_value": 99999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "o3"
    },
    # CO
    # calculated from ppm to ug/m3 with T=22C
    {
        "abbreviation": "G",
        "lower_threshold_value": 0.0,
        "upper_threshold_value": 5088.99,
        "description": "Good",
        "background_colour": "#00E400",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    }, {
        "abbreviation": "M",
        "lower_threshold_value": 5089.0,
        "upper_threshold_value": 10872.99,
        "description": "Moderate",
        "background_colour": "#FFFF00",
        "foreground_colour": "#000000",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    }, {
        "abbreviation": "Us",
        "lower_threshold_value": 10873.0,
        "upper_threshold_value": 14342.99,
        "description": "Unhealthy for sensitive groups",
        "background_colour": "#FF7E00",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    }, {
        "abbreviation": "U",
        "lower_threshold_value": 14343.0,
        "upper_threshold_value": 17812.99,
        "description": "Unhealthy",
        "background_colour": "#FF0000",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    }, {
        "abbreviation": "VU",
        "lower_threshold_value": 17813.0,
        "upper_threshold_value": 35162.99,
        "description": "Very Unhealthy",
        "background_colour": "#8F3F97",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    }, {
        "abbreviation": "H",
        "lower_threshold_value": 35163.0,
        "upper_threshold_value": 999999.0,
        "description": "Hazardous",
        "background_colour": "#7E0023",
        "foreground_colour": "#FFFFFF",
        "aqi_organization_id": "USEPA",
        "pollutant": "co"
    },
]


def insert_aqi_categories(apps, schema_editor):
    AQICategoryThreshold = apps.get_model(
        'common', 'AQICategoryThreshold')
    for aqi in AQI_CATEGORY_THRESHOLDS:
        AQICategoryThreshold.objects.get_or_create(**aqi)


def revert_aqi_categories(apps, schema_editor):
    AQICategoryThreshold = apps.get_model(
        'common', 'AQICategoryThreshold')
    AQICategoryThreshold.objects.filter(aqi_organization_id="USEPA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_eu_aqi_index_tables_data'),
    ]

    operations = [
        migrations.RunPython(insert_aqi_categories, revert_aqi_categories),
    ]
