# Generated by Django 2.1.5 on 2019-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0002_fire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_scats_site', models.PositiveIntegerField(verbose_name='NB Scats Site')),
                ('qt_interval_count', models.DateTimeField(verbose_name='QT Interval Count')),
                ('region_name', models.CharField(max_length=3, verbose_name='Region Name')),
                ('records_count', models.PositiveIntegerField(verbose_name='Records Count')),
                ('traffic_volume', models.PositiveIntegerField(verbose_name='Traffic Volume')),
            ],
            options={
                'verbose_name': 'Traffic Flow',
                'verbose_name_plural': 'Traffic Flows',
                'db_table': 'traffic_flow',
                'ordering': ('-qt_interval_count', 'region_name'),
            },
        ),
    ]
