# Generated by Django 2.1.5 on 2019-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_trafficflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficStation',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Station ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True, verbose_name='Name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Traffic Station',
                'verbose_name_plural': 'Traffic Station',
                'db_table': 'traffic_station',
                'ordering': ('name',),
            },
        ),
    ]
