# Generated by Django 2.1.5 on 2019-05-11 13:42

from django.db import migrations

STATIONS = [
    {
        'station_id': '118',
        'name': 'HULL/MOOROOLBARK',
        'longitude': 145.330288,
        'latitude': -37.775306
    },
    {
        'station_id': '4653',
        'name': 'GRANGE/WINGROVE',
        'longitude': 145.025160,
        'latitude': -37.779034
    },
    {
        'station_id': '4419',
        'name': 'NICHOLSON/GERTRUDE',
        'longitude': 144.973644,
        'latitude': -37.805414
    },
    {
        'station_id': '4405',
        'name': 'VICTORIA/RATHDOWNE',
        'longitude': 144.968816,
        'latitude': -37.807279
    },
    {
        'station_id': '4404',
        'name': 'VICTORIA/LYGON',
        'longitude': 144.965823,
        'latitude': -37.806991
    },
    {
        'station_id': '4406',
        'name': 'VICTORIA/NICHOLSON',
        'longitude': 144.973129,
        'latitude': -37.807940
    }
]


def insert_stations(apps, schema_editor):
    TrafficStation = apps.get_model(
        'geo_data', 'TrafficStation')
    for ts in STATIONS:
        TrafficStation.objects.get_or_create(**ts)


def revert_stations(apps, schema_editor):
    TrafficStation = apps.get_model(
        'geo_data', 'TrafficStation')
    TrafficStation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0004_trafficstation'),
    ]

    operations = [
        migrations.RunPython(insert_stations, revert_stations),
    ]
