# Generated by Django 2.1.5 on 2019-05-13 07:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0005_auto_20190511_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficstation',
            name='path',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Path'),
        ),
    ]
