# Generated by Django 2.1.5 on 2019-02-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(blank=True, null=True, verbose_name='Id Number')),
                ('code', models.CharField(blank=True, max_length=31, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('monitor_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Monitor ID')),
                ('short_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Short Name')),
                ('common_name', models.CharField(blank=True, max_length=31, null=True, verbose_name='Common Name')),
                ('epa_description_url', models.URLField(blank=True, null=True, verbose_name='EPA Description URL')),
                ('unit_of_measure', models.CharField(blank=True, max_length=15, null=True, verbose_name='Unit Of Measure')),
                ('presentation_precision', models.PositiveSmallIntegerField(default=0, verbose_name='Presentation Precision')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='au_epa_data.EquipmentType', verbose_name='Has Incident')),
                ('sites', models.ManyToManyField(related_name='monitors', to='au_epa_data.Site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitors',
                'db_table': 'monitor',
            },
        ),
    ]
