# Generated by Django 2.1.5 on 2019-02-15 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0002_equipmenttype_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTimeBasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_pollutant_standard', models.FloatField(blank=True, null=True, verbose_name='AQI Pollutant Standard')),
                ('incident_type', models.CharField(blank=True, max_length=31, null=True, verbose_name='Incident Type')),
                ('presentation_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presentation Order')),
                ('calc_aqi', models.BooleanField(default=False, verbose_name='Calc AQI')),
                ('calc_health_category', models.BooleanField(default=False, verbose_name='Calc Health Category')),
            ],
            options={
                'verbose_name': 'Monitor Has Time Basis',
                'verbose_name_plural': 'Monitor Has Time Basis',
                'db_table': 'monitor_time_basis',
            },
        ),
        migrations.CreateModel(
            name='TimeBasis',
            fields=[
                ('time_base_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Time Base Id')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
                ('is_rolling_average', models.PositiveSmallIntegerField(default=0, verbose_name='Is Rolling Average')),
                ('rolling_average_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rolling Average Period')),
                ('min_data_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Min Data Percent')),
                ('time_basis_desc_url', models.URLField(blank=True, null=True, verbose_name='Time Basis Desc URL')),
                ('sites', models.ManyToManyField(related_name='time_basis', to='au_epa_data.Site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': 'Time Basis',
                'verbose_name_plural': 'Time Basis',
                'db_table': 'time_basis',
            },
        ),
        migrations.AlterField(
            model_name='monitor',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='au_epa_data.EquipmentType', verbose_name='Equipment Type'),
        ),
        migrations.AddField(
            model_name='monitortimebasis',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_time_basis', to='au_epa_data.Monitor', verbose_name='Monitor Id'),
        ),
        migrations.AddField(
            model_name='monitortimebasis',
            name='time_basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor_time_basis', to='au_epa_data.TimeBasis', verbose_name='Time Basis Id'),
        ),
    ]
