# Generated by Django 2.1.5 on 2019-02-15 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0003_auto_20190215_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategoryThreshold',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Level')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Threshold Value')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
                ('value_range', models.CharField(blank=True, max_length=63, null=True, verbose_name='Value Range')),
                ('visibility', models.CharField(blank=True, max_length=63, null=True, verbose_name='Visibility')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Message')),
                ('background_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Background Colour')),
                ('foreground_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Foreground Colour')),
            ],
            options={
                'verbose_name': 'Monitor Has Time Basis',
                'verbose_name_plural': 'Monitor Has Time Basis',
                'db_table': 'health_category_threshold',
            },
        ),
    ]
