# Generated by Django 2.1.5 on 2019-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0004_healthcategorythreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQICategoryThreshold',
            fields=[
                ('abbreviation', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Abbrevation')),
                ('lower_threshold_value', models.FloatField(blank=True, null=True, verbose_name='Lower Threshold Value')),
                ('upper_threshold_value', models.FloatField(blank=True, null=True, verbose_name='Upper Threshold Value')),
                ('description', models.CharField(blank=True, max_length=63, null=True, verbose_name='Description')),
                ('background_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Background Colour')),
                ('foreground_colour', models.CharField(blank=True, max_length=7, null=True, verbose_name='Foreground Colour')),
            ],
            options={
                'verbose_name': 'AQI Category Threshold',
                'verbose_name_plural': 'AQI Category Thresholds',
                'db_table': 'aqi_category_threshold',
            },
        ),
        migrations.AlterModelOptions(
            name='healthcategorythreshold',
            options={'verbose_name': 'Health Category Threshold', 'verbose_name_plural': 'Health Category Thresholds'},
        ),
    ]
