# Generated by Django 2.1.5 on 2019-05-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0005_monitor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='aqi_category_threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='AQI Category'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='health_category_threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Health Category'),
        ),
    ]
