# Generated by Django 2.1.5 on 2019-05-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0006_auto_20190506_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='au_epa_data.EquipmentType', verbose_name='Equipment Type'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='au_epa_data.Monitor', verbose_name='Monitor'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='monitor_time_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='au_epa_data.MonitorTimeBasis', verbose_name='Monitor Time Basis'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='au_epa_data.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time_basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measurements', to='au_epa_data.TimeBasis', verbose_name='Time Basis'),
        ),
    ]
