# Generated by Django 2.1.5 on 2019-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au_epa_data', '0006_auto_20190215_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True),
        ),
    ]
