# Generated by Django 2.1.5 on 2019-04-01 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aqi_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.AQIOrganization', verbose_name='Preferred AQI scale'),
        ),
    ]
