# Generated by Django 2.1.5 on 2019-04-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_questionnaire_data'),
        ('accounts', '0004_userprofilequestionnaireanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutantSensitivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Neutral'), (1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Extremeley high')], default=0, verbose_name='Sensitivity Level')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_levels', to='common.Pollutant', verbose_name='Pollutant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_levels', to='accounts.UserProfile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Pollutant Sensitivity Level',
                'verbose_name_plural': 'Pollutant Sensitivity Levels',
                'db_table': 'pollutant_sensitivity',
            },
        ),
    ]
