# Generated by Django 2.1.5 on 2019-05-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_visualisationtool'),
        ('accounts', '0005_pollutantsensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vis_tool',
            field=models.ForeignKey(default='Gauges', on_delete=django.db.models.deletion.DO_NOTHING, to='common.VisualisationTool', verbose_name='Preferred Vis. tool'),
        ),
    ]
